import type { AccountType } from '@/src/db/schema';

/**
 * Nama tampilan yang familier bagi pengguna Indonesia. Katalog bank disusun dari
 * direktori Bank Umum dan Syariah OJK; nama produk digital ditampilkan dengan
 * merek konsumennya agar mudah ditemukan.
 */
export const ACCOUNT_NAME_OPTIONS: Record<AccountType, readonly string[]> = {
  cash: ['Dompet', 'Kas'],
  bank: [
    'BCA',
    'BRI',
    'Mandiri',
    'BNI',
    'BTN',
    'BSI',
    'CIMB Niaga',
    'Danamon',
    'PermataBank',
    'Maybank',
    'OCBC',
    'PaninBank',
    'UOB',
    'Bank Mega',
    'Bank Sinarmas',
    'Bank Muamalat',
    'BCA Syariah',
    'Jenius',
    'Bank Jago',
    'SeaBank',
    'Bank Neo Commerce',
    'Allo Bank',
    'blu by BCA Digital',
    'Bank Saqu',
    'Superbank',
    'Bank Raya',
    'Bank Aladin Syariah',
    'KB Bank',
    'KB Bank Syariah',
    'Bank Mega Syariah',
    'Panin Dubai Syariah',
    'Bank Nano Syariah',
    'Bank Victoria',
    'Bank Victoria Syariah',
    'Bank Capital',
    'Bank Artha Graha',
    'Bank Bumi Arta',
    'Bank Ganesha',
    'Bank Ina',
    'Bank Maspion',
    'Bank Mestika',
    'Bank Mayapada',
    'Bank Sahabat Sampoerna',
    'Bank Woori Saudara',
    'Bank SBI Indonesia',
    'J Trust Bank',
    'Bank Amar',
    'Bank Nationalnobu',
    'Bank KEB Hana',
    'Bank CTBC Indonesia',
    'Bank ICBC Indonesia',
    'DBS Indonesia',
    'HSBC Indonesia',
    'Standard Chartered',
    'Bank of China',
    'Bank Mizuho Indonesia',
    'MUFG Bank',
    'Bank Aceh Syariah',
    'Bank Sumut',
    'Bank Nagari',
    'Bank Riau Kepri Syariah',
    'Bank Sumsel Babel',
    'Bank Bengkulu',
    'Bank Lampung',
    'Bank Jambi',
    'Bank DKI',
    'Bank BJB',
    'Bank BJB Syariah',
    'Bank Jateng',
    'Bank DIY',
    'Bank Jatim',
    'Bank Kalbar',
    'Bank Kalteng',
    'Bank Kalsel',
    'Bank Kaltimtara',
    'Bank Sulselbar',
    'Bank SulutGo',
    'Bank Sulteng',
    'Bank Sultra',
    'Bank Maluku Malut',
    'Bank Papua',
    'Bank NTT',
    'Bank NTB Syariah',
    'Bank Bali',
  ],
  ewallet: [
    'GoPay',
    'OVO',
    'DANA',
    'ShopeePay',
    'LinkAja',
    'i.saku',
    'DOKU',
    'Sakuku',
    'AstraPay',
    'MotionPay',
    'JakOne Pay',
    'Mandiri e-money',
    'BCA Flazz',
    'BRIZZI',
    'BNI TapCash',
  ],
};
